name: FLASK CI

on:
  push:
  branches: 
   - main

jobs: 
  build: 
   runs-on: ubuntu-latest
   steps: 
     - name: Checkout Repository
       uses: actions/checkout@v4
     - name: Verify Runner
       run: echo "Github Action is working!"
